version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./docker/database/data/:/data
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo1:
    build: docker/database/
    volumes:
      - ./docker/database/data/:/example-data
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --replSet my-mongo-set --keyFile /mongo.keyfile

  mongo2:
    build: docker/database/
    volumes:
      - ./docker/database/data/:/example-data
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --replSet my-mongo-set --keyFile /mongo.keyfile

  mongo3:
    build: docker/database/
    volumes:
      - ./docker/database/data/:/example-data
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --replSet my-mongo-set --keyFile /mongo.keyfile

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
