services:
  mongo:
      image: mongo-express
      restart: always
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: root
        ME_CONFIG_MONGO_URL: mongodb://root:root@mongo:27017
      ports:
        - 8081:8081
